// Curated content for the Ideas and Activities tabs. Plain data, edit freely.

export const IDEA_CATS = {
  food: '🍜 Food', outdoors: '🌿 Outdoors', home: '🛋️ At home', creative: '🎨 Creative', adventure: '⚡ Active', chill: '☁️ Slow & chill',
};
// Rough total for two people (MyKad prices where it matters). Every idea stays under RM150.
export const COST = ['Free', 'Under RM50', 'RM50–100', 'RM100–150'];
export const HOME = 'Altris Residence, Wangsa Maju';

// [emoji, title, tip, category, cost band 0-3, place (for maps) or null for at home, minutes by car from Wangsa Maju]
// All daytime. Drive times are off-peak estimates; add buffer for KL traffic.
const BASE = [
  ['🍛', 'Kampung Baru breakfast hunt', 'Nasi lemak, roti and kuih from three different stalls. Vote on the best.', 'food', 1, 'Kampung Baru, Kuala Lumpur', 15],
  ['🏮', 'Petaling Street + Kwai Chai Hong', 'Old-school breakfast in Chinatown, then photos in the painted lane.', 'food', 1, 'Kwai Chai Hong, Kuala Lumpur', 20],
  ['🍌', 'Banana leaf lunch', 'Brickfields has the best ones. Eat with your hands.', 'food', 1, 'Brickfields, Kuala Lumpur', 25],
  ['☕', 'Bangsar café hop', 'Two cafés, one pastry each, ranked out of 10.', 'food', 2, 'Bangsar, Kuala Lumpur', 25],
  ['🥟', 'Dim sum brunch in Kepong', 'Each orders one thing the other has never tried.', 'food', 1, 'Kepong, Kuala Lumpur', 25],
  ['🧋', 'Bubble tea ranking in SS15', 'Try four shops on one street and crown a winner.', 'food', 1, 'SS15, Subang Jaya', 40],
  ['🍨', 'Dessert crawl in Bukit Bintang', 'Cendol, ice cream and one fancy cake. No mains allowed.', 'food', 2, 'Bukit Bintang, Kuala Lumpur', 20],
  ['🥐', 'TTDI bakery morning', 'Pick up pastries and eat them in TTDI park.', 'food', 1, 'Taman Tun Dr Ismail, Kuala Lumpur', 30],
  ['🍜', 'Pan mee and old-town walk in Kuala Kubu Bharu', 'A sleepy heritage town an hour away. Lunch, then the dam lookout.', 'food', 1, 'Kuala Kubu Bharu', 60],
  ['🍳', 'Cook-off at home', 'Same ingredients from the market, two dishes, honest judging.', 'home', 1, null, 0],
  ['🧺', 'Picnic at Titiwangsa lake', 'Bring a mat, rent a pedal boat, watch the KL Tower view.', 'outdoors', 1, 'Taman Tasik Titiwangsa', 10],
  ['🌺', 'Perdana Botanical Gardens', 'Shady paths, the orchid and hibiscus gardens, and a lake for a picnic.', 'outdoors', 0, 'Perdana Botanical Gardens', 25],
  ['🌳', 'KL Forest Eco Park canopy walk', 'Rainforest in the middle of the city. About RM10 each with MyKad. Closed Fridays.', 'outdoors', 1, 'KL Forest Eco Park', 20],
  ['🌲', 'FRIM Forest Skywalk', 'Treetop walkway in Kepong. Go early before it gets hot.', 'outdoors', 1, 'FRIM Kepong', 30],
  ['🥾', 'Bukit Tabur sunrise hike', 'Very close to Melawati. Steep and rocky, so wear grippy shoes and check the trail is open first.', 'outdoors', 0, 'Bukit Tabur West, Taman Melawati', 15],
  ['🛕', 'Batu Caves morning', 'Climb the rainbow stairs before the crowds and the heat. Free.', 'outdoors', 0, 'Batu Caves', 20],
  ['💦', 'Kanching waterfall', 'Seven tiers of waterfalls in Rawang. Bring a change of clothes.', 'outdoors', 1, 'Kanching Rainforest Waterfall', 35],
  ['🏞️', 'Sungai Gabai waterfall', 'Short walk to cool pools in Hulu Langat. Go on a weekday if you can.', 'outdoors', 0, 'Sungai Gabai Waterfall, Hulu Langat', 45],
  ['🚲', 'Putrajaya lake cycle', 'Rent bikes and ride around the lake and bridges.', 'outdoors', 1, 'Putrajaya Lake', 45],
  ['🌄', 'Bukit Gasing trail', 'Easy forest trail in PJ with a suspension bridge.', 'outdoors', 0, 'Bukit Gasing Forest Park', 30],
  ['🦜', 'KL Bird Park', 'Walk-in aviaries with free-flying birds. Feed the lorikeets.', 'outdoors', 2, 'KL Bird Park', 20],
  ['🦒', 'Zoo Negara', 'Ten minutes away in Hulu Kelang. Go at opening time while the animals are active.', 'outdoors', 2, 'Zoo Negara', 15],
  ['🏔️', 'Genting day trip by Awana SkyWay', 'Cable car up through the clouds, cool air and a hot drink at the top.', 'outdoors', 2, 'Awana SkyWay, Genting Highlands', 55],
  ['🌊', 'Janda Baik river day', 'Lunch by the river and a dip in the stream.', 'outdoors', 2, 'Janda Baik', 50],
  ['🎬', 'Movie marathon at home', 'Blanket fort, a trilogy and too many snacks.', 'home', 0, null, 0],
  ['🧩', 'Puzzle afternoon', 'A 1000-piece puzzle and a long playlist.', 'home', 1, null, 0],
  ['🎲', 'Board game day', 'Loser does the dishes.', 'home', 0, null, 0],
  ['💆', 'Spa day at home', 'Face masks, nail painting and foot rubs.', 'home', 1, null, 0],
  ['🍕', 'Pizza from scratch', 'Make the dough together, each designs a pizza.', 'home', 1, null, 0],
  ['🎤', 'Living room karaoke', 'YouTube karaoke and a hairbrush microphone.', 'home', 0, null, 0],
  ['💌', 'Time capsule letters', 'Write each other a letter to open in a year.', 'home', 0, null, 0],
  ['❓', 'The 36 questions', 'Take turns with the famous “36 questions that lead to love”.', 'home', 0, null, 0],
  ['🎨', 'Canvas painting workshop', 'Two hours, one canvas each, paint each other or the same view.', 'creative', 3, 'canvas painting workshop Kuala Lumpur', 25],
  ['🕯️', 'Candle making workshop', 'Pick scents for each other and take the candles home.', 'creative', 3, 'candle making workshop Kuala Lumpur', 25],
  ['🌱', 'Terrarium workshop', 'Build a tiny jungle in a jar, one each.', 'creative', 3, 'terrarium workshop Kuala Lumpur', 25],
  ['🛍️', 'Bundle thrift challenge', 'RM20 each to build an outfit for the other at the bundle shops.', 'creative', 1, 'bundle shop Setapak Wangsa Maju', 10],
  ['📚', 'Bookstore swap at Kinokuniya', 'Pick a book for each other and read the first page in the shop.', 'creative', 2, 'Kinokuniya KLCC', 20],
  ['📸', 'Photo walk at Merdeka Square', 'Take 10 photos of each other around Dataran Merdeka and Masjid Jamek.', 'creative', 0, 'Dataran Merdeka', 20],
  ['🖼️', 'ILHAM Gallery', 'Free contemporary art gallery. Pretend to be serious art critics.', 'creative', 0, 'ILHAM Gallery', 20],
  ['🧗', 'Bouldering session', 'Day pass plus shoe rental is about RM40 each. Cheer each other up the beginner walls.', 'adventure', 2, 'bouldering gym Kuala Lumpur', 25],
  ['⛸️', 'Ice skating at Sunway Pyramid', 'Hold hands, mostly to stay upright.', 'adventure', 2, 'Sunway Pyramid Ice', 35],
  ['🎳', 'Bowling', 'Best of three. Loser buys lunch.', 'adventure', 1, 'bowling Kuala Lumpur', 20],
  ['🕹️', 'Arcade battle', 'Best of five games at a mall arcade. Loser buys bubble tea.', 'adventure', 1, 'arcade Kuala Lumpur', 15],
  ['🔐', 'Escape room', 'Find out how well you work together under pressure.', 'adventure', 3, 'escape room Kuala Lumpur', 25],
  ['🏸', 'Badminton', 'Book a court for an hour. Trash talk encouraged.', 'adventure', 1, 'badminton court Wangsa Maju', 10],
  ['🚇', 'Random LRT stop', 'Ride from Wangsa Maju station and get off somewhere neither of you has been.', 'adventure', 1, 'Wangsa Maju LRT station', 5],
  ['🔬', 'Petrosains', 'Interactive science museum in KLCC. Surprisingly fun for adults.', 'chill', 1, 'Petrosains KLCC', 20],
  ['🏙️', 'KLCC Park stroll', 'Walk the park under the towers, then cool down in the mall.', 'chill', 0, 'KLCC Park', 20],
  ['🛕', 'Thean Hou Temple', 'Red lanterns and city views from the hill. Free to visit.', 'chill', 0, 'Thean Hou Temple', 25],
  ['🏛️', 'National Museum', 'Cheap entry with MyKad and a quiet afternoon of history.', 'chill', 1, 'Muzium Negara', 25],
  ['📖', 'REXKL afternoon', 'An old cinema turned bookshop and creative space. Free to wander.', 'chill', 0, 'REXKL', 20],
  ['🍵', 'Tea house afternoon', 'Share a pot of Chinese tea and snacks in Chinatown.', 'chill', 1, 'tea house Petaling Street', 20],
  ['🎞️', 'Matinee movie', 'Cheaper daytime tickets and an empty cinema.', 'chill', 1, 'cinema Wangsa Walk Mall', 5],
  ['👣', 'Foot reflexology', 'An hour of foot massage side by side.', 'chill', 3, 'foot reflexology Kuala Lumpur', 15],
  ['🧘', 'Yoga in the park', 'Follow a beginner video on the grass, then brunch.', 'chill', 0, 'Taman Tasik Titiwangsa', 10],
  ['🎶', 'Shared playlist afternoon', 'Take turns adding songs that remind you of each other.', 'home', 0, null, 0],
];


// 🔥 Trending picks (Oct 2026): what couples are posting about, mapped onto KL. Same rules: daytime, <1h from home, <RM150 for two.
const HOT = [
  ['📸', 'Self-photo studio session', 'Korean-style self-shoot with fun backdrops. Sessions are about RM60–80 for both of you.', 'creative', 2, 'self photo studio Kuala Lumpur', 20],
  ['🎞️', 'Photo booth crawl', 'Hit three photo booths in one afternoon and keep every strip in a jar.', 'creative', 1, 'photo booth Bukit Bintang', 20],
  ['📿', 'Matching bead bracelets', 'Make bracelets with each other’s initials at a bead bar.', 'creative', 2, 'bead bracelet workshop Kuala Lumpur', 25],
  ['🔑', 'Bag charm making', 'Build a charm for each other’s bag or keys.', 'creative', 1, 'charm making workshop Kuala Lumpur', 25],
  ['🌊', 'Resin coaster workshop', 'Pour ocean-style resin coasters and take them home.', 'creative', 3, 'resin art workshop Kuala Lumpur', 20],
  ['🧶', 'Mini tufting class', 'Try the tufting gun on a small rug or coaster.', 'creative', 3, 'tufting workshop Kuala Lumpur', 25],
  ['🖌️', 'Batik painting at Central Market', 'Paint your own batik piece. Small designs start around RM15.', 'creative', 1, 'Central Market Kuala Lumpur', 20],
  ['🏺', 'Paint-your-own ceramics', 'Paint a ready-made mug for each other. Cheaper than a pottery class.', 'creative', 3, 'paint your own pottery Kuala Lumpur', 25],
  ['🖼️', 'Immersive art gallery', 'Walk-in light and projection rooms made for photos.', 'creative', 2, 'immersive art gallery Kuala Lumpur', 20],
  ['📷', 'Disposable camera day', 'Shoot 27 frames of each other, then develop them together a week later.', 'creative', 2, 'film photo lab Kuala Lumpur', 20],
  ['📚', 'Blind date with a book', 'Some bookshops wrap books in paper. Pick a mystery one for each other.', 'creative', 1, 'indie bookstore Kuala Lumpur', 20],
  ['📖', 'BookXcess haul', 'Huge discount bookstore. RM30 each, pick books for each other.', 'creative', 1, 'BookXcess Gamuda Walk', 45],
  ['🎵', 'Vinyl digging', 'Browse a record shop and pick one record for each other.', 'creative', 1, 'record store Kuala Lumpur', 20],
  ['🪴', 'Plant nursery trip', 'Choose a plant to raise together at the Sungai Buloh nurseries.', 'creative', 1, 'Sungai Buloh plant nursery', 35],
  ['🎨', 'Street art walk', 'Murals around Jalan Panggung and Chinatown back lanes.', 'creative', 0, 'Jalan Panggung Kuala Lumpur', 20],
  ['🕌', 'Putrajaya photo walk', 'The pink mosque, the bridges and the lake. Bring a hat.', 'creative', 0, 'Masjid Putra', 45],
  ['📍', 'Polaroid scavenger hunt', 'Write 10 things to photograph (a red door, a cat, a mural…) and race around town.', 'creative', 0, 'Kuala Lumpur city centre', 20],
  ['🎬', 'Film a “day in our life” vlog', 'Shoot little clips all day and edit them together at night.', 'creative', 0, null, 0],
  ['🛍️', 'Car boot sale hunt', 'Look for vintage treasures with RM20 each.', 'creative', 1, 'car boot sale Kuala Lumpur', 25],
  ['🎭', 'Weekend matinee at KLPAC', 'A daytime play or musical at the performing arts centre.', 'creative', 3, 'KLPAC Sentul', 15],
  ['🍵', 'Matcha crawl', 'Three matcha spots, rank them out of 10.', 'food', 2, 'matcha cafe Kuala Lumpur', 20],
  ['🥐', 'Croissant hunt in Bangsar', 'Find the flakiest croissant. Crumbs everywhere.', 'food', 1, 'Bangsar', 25],
  ['🏚️', 'Kampung Attap café morning', 'Old-shophouse cafés around Zhongshan Building.', 'food', 2, 'Zhongshan Building Kampung Attap', 20],
  ['☕', 'Taman OUG café hop', 'A quieter café neighbourhood with new bakeries.', 'food', 2, 'Taman OUG', 30],
  ['🫓', 'Mamak breakfast', 'Roti canai and teh tarik nearby. Rate the roti.', 'food', 1, 'mamak Wangsa Maju', 5],
  ['🍲', 'Steamboat lunch', 'Share one pot and fight over the fishballs.', 'food', 2, 'steamboat Kuala Lumpur', 20],
  ['🥩', 'Korean BBQ lunch set', 'Lunch sets are cheaper than dinner. Grill for each other.', 'food', 3, 'korean bbq Mont Kiara', 25],
  ['🍰', 'Cheesecake taste test', 'Basque, Japanese or New York? Settle it.', 'food', 2, 'cheesecake cafe Kuala Lumpur', 20],
  ['🍨', 'Gelato flight', 'Pick six flavours between you and swap spoons.', 'food', 1, 'gelato Bangsar', 25],
  ['🫖', 'Afternoon tea for two', 'Share one tiered tea set.', 'food', 3, 'afternoon tea Kuala Lumpur', 20],
  ['🍛', 'Nasi kandar showdown', 'Two shops, same order, one winner.', 'food', 1, 'nasi kandar Kuala Lumpur', 20],
  ['🧊', 'Cendol and ABC break', 'Cool down with shaved ice desserts.', 'food', 1, 'cendol Kuala Lumpur', 20],
  ['🍞', 'Kopitiam crawl', 'Kaya toast, half-boiled eggs and kopi at old Chinatown kopitiams.', 'food', 1, 'kopitiam Petaling Street', 20],
  ['🥬', 'Market to table', 'Shop the morning market together, then cook what you bought.', 'food', 1, 'pasar pagi Wangsa Maju', 5],
  ['🧺', 'Picnic at TRX City Park', 'Rooftop park above The Exchange TRX with skyline views.', 'food', 1, 'TRX City Park', 20],
  ['🌳', 'Desa ParkCity lakeside picnic', 'Lake, lawns and cafés in one place.', 'food', 1, 'Desa ParkCity', 30],
  ['🥭', 'Durian date (in season)', 'Share a few kinds and argue about the best one.', 'food', 2, 'durian SS2 Petaling Jaya', 30],
  ['🍜', 'Ramen hopping', 'Split two bowls at two shops.', 'food', 2, 'ramen Kuala Lumpur', 20],
  ['🌿', 'Greenhouse café', 'Brunch among the plants.', 'food', 2, 'greenhouse cafe Kuala Lumpur', 25],
  ['🧋', 'DIY boba at home', 'Cook tapioca pearls and make your own bubble tea.', 'home', 1, null, 0],
  ['🍣', 'Sushi rolling at home', 'Buy nori and fillings and roll for each other.', 'home', 2, null, 0],
  ['🥟', 'Dumpling folding', 'Fold dumplings together; ugly ones count.', 'home', 1, null, 0],
  ['🍡', 'Mochi making', 'Simple microwave mochi with your favourite fillings.', 'home', 1, null, 0],
  ['🧁', 'Cupcake decorating battle', 'Plain cupcakes, lots of icing, judge each other’s.', 'home', 1, null, 0],
  ['🍳', 'Copy a café dish', 'Recreate a café brunch at home and rate it.', 'home', 1, null, 0],
  ['🍜', 'Instant noodle taste test', 'Five packs from the shop, blind tasting.', 'home', 1, null, 0],
  ['🖍️', 'Colouring date', 'A viral one: two colouring books, markers and a playlist.', 'home', 1, null, 0],
  ['🌼', 'Pressed flower frames', 'Press flowers in a heavy book and frame them together.', 'home', 1, null, 0],
  ['🧱', 'LEGO flower bouquet', 'Build a bouquet that never wilts.', 'home', 2, null, 0],
  ['🪡', 'Embroidery hoops', 'Stitch each other’s initials.', 'home', 1, null, 0],
  ['🎨', 'Paint by numbers', 'One big canvas, two halves.', 'home', 1, null, 0],
  ['📼', 'First-date movie rewatch', 'Watch the film from your early dates again.', 'home', 0, null, 0],
  ['🖼️', 'Recreate your first photo', 'Find your oldest photo together and recreate it exactly.', 'home', 0, null, 0],
  ['💃', 'Learn a TikTok dance', 'Pick a couple dance trend and nail it by tonight.', 'home', 0, null, 0],
  ['🎙️', 'Record a fake podcast', 'Episode 1: “How we met”. Interview each other.', 'home', 0, null, 0],
  ['🔮', 'Vision board', 'Cut and paste the things you want to do together next year.', 'home', 1, null, 0],
  ['✅', 'Yes day', 'One person plans the day; the other says yes to everything (within reason).', 'home', 1, null, 0],
  ['📒', 'Date scrapbook', 'Print photos from your memories and fill a scrapbook.', 'home', 1, null, 0],
  ['🗺️', 'Home scavenger hunt', 'Hide clues around the house that lead to a small gift.', 'home', 0, null, 0],
  ['📺', 'K-drama binge', 'Korean snacks, one new series, no spoilers.', 'home', 1, null, 0],
  ['🎂', 'Bake a monthsary cake', 'Bake together on the 12th and light a candle.', 'home', 1, null, 0],
  ['🌄', 'Broga Hill sunrise', 'The famous sunrise hike. Leave around 5am and bring a torch.', 'outdoors', 0, 'Broga Hill', 55],
  ['✈️', 'Plane spotting at Anjung Spotter', 'Watch planes land and take off near KLIA. Pack snacks.', 'outdoors', 0, 'Anjung Spotter', 55],
  ['🌸', 'Putrajaya Botanical Garden', 'Big gardens, shady paths and a lake.', 'outdoors', 0, 'Taman Botani Putrajaya', 45],
  ['🦆', 'Putrajaya Wetlands', 'Boardwalks and birds. Go in the morning.', 'outdoors', 0, 'Taman Wetland Putrajaya', 45],
  ['🌲', 'Taman Rimba Kiara walk', 'Easy forest loop with city views.', 'outdoors', 0, 'Taman Rimba Kiara', 30],
  ['🍃', 'Kepong Metropolitan Park', 'Lake, cycling paths and lots of space.', 'outdoors', 0, 'Kepong Metropolitan Park', 25],
  ['🌳', 'Taman Tugu forest trail', 'A rainforest trail right in the city.', 'outdoors', 0, 'Taman Tugu', 20],
  ['🥾', 'Bukit Saga hike', 'Popular Cheras trail with a view at the top.', 'outdoors', 0, 'Bukit Saga Cheras', 25],
  ['🏞️', 'Templer Park waterfalls', 'Short walks to cool pools near Rawang.', 'outdoors', 0, 'Templer Park Rawang', 35],
  ['🏡', 'Colmar Tropicale', 'French-village look and a Japanese garden up at Bukit Tinggi.', 'outdoors', 2, 'Colmar Tropicale', 55],
  ['🌊', 'Ulu Yam river day', 'Riverside picnic, then the famous loh mee.', 'outdoors', 1, 'Ulu Yam', 40],
  ['🌉', 'Saloma Link bridge walk', 'The light-up bridge with KLCC views.', 'outdoors', 0, 'Saloma Link', 20],
  ['📖', 'Hammock and book at Taman Tasik Permaisuri', 'Find a shady tree and read.', 'outdoors', 0, 'Taman Tasik Permaisuri', 20],
  ['🏃', 'Coffee run club', 'Join a Saturday social 5K, then coffee. Huge trend this year.', 'adventure', 1, 'run club Kuala Lumpur', 20],
  ['🏓', 'Pickleball', 'Rent a court and paddles for an hour. Easy to learn.', 'adventure', 2, 'pickleball court Kuala Lumpur', 20],
  ['🎾', 'Padel', 'Book a court for an hour and split it.', 'adventure', 3, 'padel court Kuala Lumpur', 25],
  ['🧸', 'Claw machine challenge', 'Claw machine shops are everywhere. RM20 each, most prizes wins.', 'adventure', 1, 'claw machine shop Kuala Lumpur', 15],
  ['🎤', 'Coin karaoke booth', 'Tiny karaoke booths, pay per song.', 'adventure', 1, 'coin karaoke Kuala Lumpur', 15],
  ['🥽', 'VR arcade', 'Fight zombies side by side.', 'adventure', 2, 'VR arcade Kuala Lumpur', 20],
  ['🤸', 'Trampoline park', 'Bounce like kids for an hour.', 'adventure', 2, 'trampoline park Kuala Lumpur', 25],
  ['🏹', 'Archery', 'Beginner lesson, then a friendly competition.', 'adventure', 2, 'archery range Kuala Lumpur', 20],
  ['🪓', 'Axe throwing', 'Surprisingly satisfying. Loser buys bubble tea.', 'adventure', 3, 'axe throwing Kuala Lumpur', 25],
  ['🏎️', 'Go-karting', 'A few laps each. Best lap time wins.', 'adventure', 3, 'go kart Kuala Lumpur', 30],
  ['🛼', 'Roller skating', 'Rent skates and hold on to each other.', 'adventure', 2, 'roller skating rink Kuala Lumpur', 25],
  ['⛳', 'Mini golf', 'Nine holes, keep score honestly.', 'adventure', 2, 'mini golf Kuala Lumpur', 25],
  ['🛶', 'Kayak on Putrajaya Lake', 'Paddle under the bridges.', 'adventure', 2, 'kayak Putrajaya', 45],
  ['🧘', 'Pilates drop-in class', 'Try a beginner class together.', 'adventure', 2, 'pilates class Kuala Lumpur', 20],
  ['🚝', 'Monorail loop', 'Ride the whole line and hop off anywhere that looks fun.', 'adventure', 1, 'KL Monorail', 15],
  ['🚌', 'Free GoKL bus tour', 'Hop on the free city bus and see where it takes you.', 'adventure', 0, 'GoKL City Bus', 15],
  ['🐈', 'Cat café', 'Coffee with cats on your lap.', 'chill', 1, 'cat cafe Kuala Lumpur', 20],
  ['🐠', 'Aquaria KLCC', 'The underwater tunnel. Check the MyKad price first.', 'chill', 3, 'Aquaria KLCC', 20],
  ['🌌', 'National Planetarium', 'Space shows and exhibits near the Lake Gardens.', 'chill', 1, 'National Planetarium Kuala Lumpur', 25],
  ['🎨', 'National Art Gallery', 'Free entry and a calm afternoon.', 'chill', 0, 'National Art Gallery Malaysia', 15],
  ['🕌', 'Islamic Arts Museum', 'Beautiful domes, tiles and textiles.', 'chill', 1, 'Islamic Arts Museum Malaysia', 25],
  ['👑', 'Royal Museum', 'The old palace, open to visitors.', 'chill', 1, 'Muzium Diraja', 25],
  ['🛕', 'Chinatown temple trail', 'Sri Mahamariamman, Guan Di and Sin Sze Si Ya temples in one walk.', 'chill', 0, 'Sri Mahamariamman Temple', 20],
  ['🛍️', 'Window shopping at The Exchange TRX', 'Wander the newest big mall, then the rooftop park.', 'chill', 0, 'The Exchange TRX', 20],
  ['🏔️', 'Genting Premium Outlets', 'Cool air and bargain hunting halfway up the hill.', 'chill', 1, 'Genting Highlands Premium Outlets', 50],
  ['💆', 'Thai massage for two', 'An hour side by side. About RM60–70 each.', 'chill', 3, 'thai massage Kuala Lumpur', 15],
].map(r => [...r, true]);

// Trending first, then the originals.
export const DATE_IDEAS = [...HOT, ...BASE];

const g = q => `https://www.google.com/search?q=${encodeURIComponent(q)}`;

// Things to do together, in person or from two different places. Everything here keeps the two of you under RM150.
export const ACTIVITY_GROUPS = [
  { id: 'watch', title: '🍿 Watch & listen together', blurb: 'Like Scener: press play at the same moment, even from two different homes. The tools are free, but you each need the streaming service.', items: [
    { e: '🎉', name: 'Teleparty', url: 'https://www.teleparty.com', what: 'Browser extension that syncs Netflix, Disney+, Prime Video, YouTube and more, with a chat on the side.', cost: 'Free (premium adds video chat)', on: 'Chrome, Edge, Safari' },
    { e: '🎬', name: 'Scener', url: 'https://www.scener.com', what: 'A virtual movie theatre. Watch your streaming services in sync with video chat.', cost: 'Free', on: 'Desktop browser' },
    { e: '📱', name: 'Rave', url: 'https://rave.io', what: 'Phone app for watching YouTube, Netflix and more in sync, with voice chat.', cost: 'Free', on: 'iPhone, Android' },
    { e: '🔗', name: 'Watch2Gether', url: 'https://w2g.tv', what: 'Make a room, paste YouTube or Twitch links. No account needed.', cost: 'Free', on: 'Any browser' },
    { e: '7️⃣', name: 'TwoSeven', url: 'https://twoseven.xyz', what: 'Watch YouTube, Netflix and more in sync with built-in video chat.', cost: 'Free', on: 'Desktop browser' },
    { e: '🎞️', name: 'Syncplay', url: 'https://syncplay.pl', what: 'Watch the same downloaded movie file in sync, each on your own laptop.', cost: 'Free', on: 'Windows, Mac, Linux' },
    { e: '🍎', name: 'SharePlay', url: g('SharePlay FaceTime watch together'), what: 'Built into FaceTime. Start a call, then play a show or song and it syncs for both of you.', cost: 'Free', on: 'iPhone, iPad, Mac' },
    { e: '🎧', name: 'Discord Watch Together', url: 'https://discord.com', what: 'Start a voice call and launch the YouTube Watch Together activity.', cost: 'Free', on: 'Desktop, phone' },
    { e: '🎶', name: 'Spotify Jam', url: g('Spotify Jam listen together'), what: 'One shared queue you both add songs to, played in sync.', cost: 'Premium needed to start one', on: 'Phone, desktop' },
  ] },
  { id: 'browser', title: '🎮 Play in the browser', blurb: 'Free, nothing to install. Open the link while you’re on a call.', items: [
    { e: '✏️', name: 'skribbl.io', url: 'https://skribbl.io', what: 'Draw and guess. Make a private room for just the two of you.', cost: 'Free', on: 'Any browser' },
    { e: '🦕', name: 'Drawasaurus', url: 'https://drawasaurus.org', what: 'Another draw-and-guess game with private rooms. Good on phones too.', cost: 'Free', on: 'Any browser' },
    { e: '☎️', name: 'Gartic Phone', url: 'https://garticphone.com', what: 'The telephone game with drawings. Even funnier with friends.', cost: 'Free', on: 'Any browser' },
    { e: '🖌️', name: 'PaintYourDate', url: 'https://paintyourdate.io', what: 'Draw together on a shared canvas, made for couples.', cost: 'Free', on: 'Any browser' },
    { e: '🃏', name: 'Board Game Arena', url: 'https://boardgamearena.com', what: 'Hundreds of real board games. Lost Cities and Patchwork are great for two.', cost: 'Free (premium optional)', on: 'Any browser' },
    { e: '🚢', name: 'Papergames', url: 'https://papergames.io', what: 'Battleship, Connect 4, Gomoku and more. Send a link, play instantly.', cost: 'Free', on: 'Any browser' },
    { e: '🌍', name: 'GeoGuessr', url: 'https://www.geoguessr.com', what: 'Dropped somewhere on Street View. Guess where you are, together or as a duel.', cost: 'Free tier, subscription', on: 'Browser, phone' },
    { e: '🗺️', name: 'Seterra', url: 'https://www.geoguessr.com/seterra', what: 'Free map quizzes. Race each other to name every country in Asia.', cost: 'Free', on: 'Any browser' },
    { e: '♟️', name: 'Lichess', url: 'https://lichess.org', what: 'Free chess with no ads. Send a challenge link and play during a call.', cost: 'Free', on: 'Browser, phone' },
    { e: '⌨️', name: 'TypeRacer', url: 'https://play.typeracer.com', what: 'Race each other by typing. Make a private race track.', cost: 'Free', on: 'Any browser' },
    { e: '🧱', name: 'Jstris', url: 'https://jstris.jezevec10.com', what: 'Tetris battles in the browser. Clear lines to send garbage at each other.', cost: 'Free', on: 'Desktop browser' },
    { e: '🏎️', name: 'Smash Karts', url: 'https://smashkarts.io', what: 'Silly kart battles in the browser. Make a private room.', cost: 'Free', on: 'Any browser' },
    { e: '🟩', name: 'Wordle + Connections', url: 'https://www.nytimes.com/games/wordle/index.html', what: 'Do the daily puzzles separately, then compare scores over dinner.', cost: 'Free', on: 'Any browser' },
    { e: '❔', name: 'Kahoot quiz about us', url: 'https://kahoot.com', what: 'Each makes a quiz about yourselves. Lowest score buys dessert.', cost: 'Free', on: 'Any browser' },
    { e: '🧠', name: 'Sporcle', url: 'https://www.sporcle.com', what: 'Thousands of trivia quizzes. Pick one and work it out together.', cost: 'Free', on: 'Any browser' },
    { e: '🧩', name: 'Jigsaw Puzzles', url: 'https://jigsawpuzzles.io', what: 'Do a jigsaw puzzle together in real time.', cost: 'Free', on: 'Any browser' },
    { e: '✨', name: 'neal.fun', url: 'https://neal.fun', what: 'Delightful little web toys. Share your screen and explore them together.', cost: 'Free', on: 'Any browser' },
  ] },
  { id: 'phone', title: '📱 Phone games for two', blurb: 'Free games you can play side by side or miles apart.', items: [
    { e: '⚔️', name: 'Mobile Legends', url: 'https://m.mobilelegends.com', what: 'Malaysia’s favourite. Queue up as a duo and carry each other.', cost: 'Free', on: 'iPhone, Android' },
    { e: '🟡', name: 'Pokémon GO', url: 'https://pokemongolive.com', what: 'Walk around a park together catching Pokémon. A daytime date in disguise.', cost: 'Free', on: 'iPhone, Android' },
    { e: '🏃', name: 'Stumble Guys', url: 'https://www.stumbleguys.com', what: 'Chaotic obstacle-course party game. Team up as a pair.', cost: 'Free', on: 'Phone, PC' },
    { e: '⭐', name: 'Brawl Stars', url: 'https://supercell.com/en/games/brawlstars/', what: 'Quick 3-minute matches. The Duo Showdown mode is made for two.', cost: 'Free', on: 'iPhone, Android' },
    { e: '🧱', name: 'Roblox', url: 'https://www.roblox.com', what: 'Endless mini games. Try a cooking, fashion or horror game together.', cost: 'Free', on: 'Phone, PC, console' },
    { e: '🌬️', name: 'Genshin Impact', url: 'https://genshin.hoyoverse.com', what: 'Explore a huge fantasy world together in co-op mode.', cost: 'Free', on: 'Phone, PC, PlayStation' },
    { e: '☁️', name: 'Sky: Children of the Light', url: 'https://www.thatskygame.com', what: 'Fly through a beautiful world together and hold hands.', cost: 'Free', on: 'Phone, Switch, PlayStation, PC' },
    { e: '🚀', name: 'Spaceteam', url: 'https://www.spaceteam.ca', what: 'Shout technobabble at each other to keep your spaceship alive. Hilarious in person.', cost: 'Free', on: 'iPhone, Android' },
    { e: '🔤', name: 'Words With Friends', url: 'https://www.wordswithfriends.com', what: 'Scrabble-style game you play one move at a time, all week.', cost: 'Free', on: 'Phone, browser' },
    { e: '🙈', name: 'Heads Up!', url: g('Heads Up app game'), what: 'Phone on your forehead, the other one acts it out. Great for road trips.', cost: 'About RM5', on: 'iPhone, Android' },
  ] },
  { id: 'games', title: '🕹️ PC & console games for two', blurb: 'Proper co-op games, chosen so the two of you spend under RM150 in total. Prices are rough Steam prices.', items: [
    { e: '🪵', name: 'It Takes Two', url: 'https://www.ea.com/games/it-takes-two', what: 'A co-op adventure made for couples. With the Friend’s Pass, one copy covers both of you online.', cost: 'One copy for two; often on sale under RM150', on: 'PC, PlayStation, Xbox, Switch' },
    { e: '🔦', name: 'We Were Here', url: g('We Were Here game Steam'), what: 'Escape-room puzzle game where you talk by walkie-talkie. The first one is free.', cost: 'Free', on: 'PC, consoles' },
    { e: '🧑‍🤝‍🧑', name: 'Pico Park', url: g('Pico Park game'), what: 'Tiny, adorable co-op puzzles that need perfect teamwork.', cost: 'About RM20 each', on: 'PC, Switch' },
    { e: '⛓️', name: 'Chained Together', url: g('Chained Together game Steam'), what: 'You’re chained together and must climb out of hell. Viral for a reason.', cost: 'About RM20 each', on: 'PC' },
    { e: '🐧', name: 'Bread & Fred', url: g('Bread & Fred game'), what: 'Two penguins tied with a rope climbing a mountain. Made for couples.', cost: 'About RM60 each', on: 'PC, consoles' },
    { e: '🤖', name: 'Biped', url: g('Biped game co-op'), what: 'Two little robots, simple controls, gentle puzzles.', cost: 'About RM40 each', on: 'PC, consoles' },
    { e: '🌀', name: 'Portal 2 co-op', url: g('Portal 2 co-op Steam'), what: 'Classic portal puzzles built for two. Very cheap on sale.', cost: 'About RM40 each', on: 'PC' },
    { e: '👻', name: 'Lethal Company', url: g('Lethal Company Steam'), what: 'Spooky scavenging on abandoned moons. Funny and scary.', cost: 'About RM45 each', on: 'PC' },
    { e: '🌾', name: 'Stardew Valley', url: 'https://www.stardewvalley.net', what: 'Run a cosy farm together at your own pace.', cost: 'About RM30 each', on: 'PC, consoles, phone' },
    { e: '👩‍🍳', name: 'Overcooked! 2', url: g('Overcooked 2'), what: 'Chaotic co-op cooking. Couch co-op on one copy.', cost: 'One copy for couch co-op', on: 'PC, consoles' },
    { e: '🧶', name: 'Unravel Two', url: g('Unravel Two game'), what: 'A gentle platformer about two yarn characters tied together. Couch co-op on one copy.', cost: 'One copy for couch co-op', on: 'PC, consoles' },
    { e: '💣', name: 'Keep Talking and Nobody Explodes', url: 'https://keeptalkinggame.com', what: 'One defuses a bomb, the other reads the manual. Only one of you buys it; the manual is free online.', cost: 'One copy for two', on: 'PC, consoles, phone' },
    { e: '🫘', name: 'Fall Guys', url: 'https://www.fallguys.com', what: 'Jelly-bean obstacle races. Squad up as a pair.', cost: 'Free', on: 'PC, consoles' },
    { e: '🏗️', name: 'Fortnite (LEGO & party modes)', url: 'https://www.fortnite.com', what: 'Skip the shooting: try LEGO Fortnite survival or the party islands together.', cost: 'Free', on: 'PC, consoles, phone' },
  ] },
  { id: 'talk', title: '💬 Talk & get closer', blurb: 'For slower nights and long-distance days.', items: [
    { e: '💞', name: 'Paired', url: 'https://www.paired.com', what: 'A daily question and quizzes for couples. You see each other’s answers.', cost: 'Free daily question, subscription', on: 'iPhone, Android' },
    { e: '🌱', name: 'Agapé', url: g('Agape couples app'), what: 'One question a day. Answers unlock once you’ve both replied.', cost: 'Free, premium optional', on: 'iPhone, Android' },
    { e: '🔥', name: 'Flamme', url: 'https://flamme.app', what: 'Couple quizzes, drawing games and daily questions in one app.', cost: 'Free, premium optional', on: 'iPhone, Android' },
    { e: '💑', name: 'Between', url: 'https://between.us', what: 'A private chat app just for the two of you, with a shared calendar and photo album.', cost: 'Free', on: 'iPhone, Android' },
    { e: '📸', name: 'Locket', url: 'https://locket.camera', what: 'Photos you send pop up on each other’s home screen widget.', cost: 'Free', on: 'iPhone, Android' },
    { e: '🧸', name: 'Widgetable', url: g('Widgetable couple app'), what: 'Cute shared widgets: a pet you raise together, notes, distance between you.', cost: 'Free, premium optional', on: 'iPhone, Android' },
    { e: '❓', name: '36 Questions That Lead to Love', url: g('36 questions that lead to love'), what: 'The famous list from the psychology study. Take turns, no skipping.', cost: 'Free', on: 'Anywhere' },
    { e: '🎬', name: 'Letterboxd', url: 'https://letterboxd.com', what: 'Log every movie you watch together and rate them separately.', cost: 'Free', on: 'Phone, browser' },
    { e: '📚', name: 'Goodreads buddy read', url: 'https://www.goodreads.com', what: 'Pick the same book and track your progress side by side.', cost: 'Free', on: 'Phone, browser' },
    { e: '📌', name: 'Pinterest shared board', url: 'https://www.pinterest.com', what: 'A shared board for your dream trips, home and outfits.', cost: 'Free', on: 'Phone, browser' },
  ] },
  { id: 'create', title: '🎨 Create, learn & explore', blurb: 'Make something together or wander the world from the sofa.', items: [
    { e: '🦉', name: 'Duolingo', url: 'https://www.duolingo.com', what: 'Learn a language together and keep each other’s streak alive.', cost: 'Free', on: 'Phone, browser' },
    { e: '🖍️', name: 'Excalidraw', url: 'https://excalidraw.com', what: 'A shared whiteboard. Plan a trip, doodle, or draw each other badly.', cost: 'Free', on: 'Any browser' },
    { e: '🎼', name: 'Write a song with Suno', url: 'https://suno.com', what: 'Describe your relationship and get an AI-made love song in seconds.', cost: 'Free tier', on: 'Browser, phone' },
    { e: '🖼️', name: 'Bob Ross paint-along', url: 'https://www.youtube.com/results?search_query=bob+ross+full+episode', what: 'Two canvases, one episode, happy little trees.', cost: 'About RM30 for supplies', on: 'YouTube' },
    { e: '🍳', name: 'Cook-along video call', url: 'https://www.youtube.com/results?search_query=easy+recipe+for+two', what: 'Pick the same recipe and cook it at the same time on a call.', cost: 'Groceries', on: 'YouTube + video call' },
    { e: '🏛️', name: 'Google Arts & Culture', url: 'https://artsandculture.google.com', what: 'Virtual tours of world museums. Pick a museum each.', cost: 'Free', on: 'Any browser' },
    { e: '🐻', name: 'Explore.org live cams', url: 'https://explore.org/livecams', what: 'Live cams of bears, puppies, aquariums and beaches. Weirdly romantic.', cost: 'Free', on: 'Any browser' },
    { e: '🌏', name: 'Google Earth tour', url: 'https://earth.google.com/web/', what: 'Fly to the places you want to visit together one day.', cost: 'Free', on: 'Browser, phone' },
    { e: '📻', name: 'Radio Garden', url: 'https://radio.garden', what: 'Spin a globe and listen to live radio anywhere. Pick a city to “visit” together.', cost: 'Free', on: 'Browser, phone' },
    { e: '🪟', name: 'WindowSwap', url: 'https://www.window-swap.com', what: 'Look out of a stranger’s window somewhere in the world. Weirdly calming.', cost: 'Free', on: 'Any browser' },
    { e: '🎓', name: 'A free short course', url: 'https://www.coursera.org', what: 'Pick one free course (photography, psychology, cooking) and do it together.', cost: 'Free to audit', on: 'Any browser' },
  ] },
];
